from os import system
from time import sleep
from random import uniform

message = {
    0: 'systemd[1]: Starting Session 2334 of user root.',
    1: 'systemd[1]: Started Session 2334 of user root.',
    2: 'CRON [6843]: (root) CHD ([ -x /opt/psa/admin/sbin/backupeng ] && /opt/psa/admin'
       '/sbin/backupung >/dev/null 2>&1)',
    3: 'systemd[1]: Starting Session 2336 of user root.',
    4: 'systemd[1]: Started Session 2336 of user root.',
    5: 'systemd[1]: Starting Session 2337 of user root.',
    6: 'systemd[1]: Started Session 2337 of user root.',
    7: 'postfix/smtpd [6694]: connect from mail.dosMail.com[192.168.0.137]',
    8: 'plesk_saslauthd[6896]: listen 6. status=5. dbpath="/plesk/passwd.db, keypath=\'/plesk'
       '/passwd_db_key\'. chroot-1, unprivileged-1',
    9: 'plesk_saslauthd[6896]: privileges set to (109:115) (effective 109:115)',
    10: 'plesk_saslauthd [6896]: failed nail authentication attempt for user \'spencer\' (password len-8)',
    11: 'postfix/sutpd [6894]: warning: mail.cocenterpriseagency.com[192.168.0.137]: SASL LOGIN authentication'
        ' failed: authentication failure',
    12: 'postfixisutpd [6894]: disconnect from mail.cocenterpriseagency.com[192.168.0.137]',
    13: 'plesk_saslauthd[6896]: select timeout, exiting',
    14: 'systemd[1]: Reloading.',
    15: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    16: 'systemd[1]: Started ACPI event daemon.',
    17: 'systemd[1]: Listening on ACPID Listen Socket.',
    18: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    19: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    20: 'systemd[1]: Mounted /.',
    21: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    22: 'systemd[1]: Found device /dev/dm-1.',
    23: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    24: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    25: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    26: 'systemd[1]: Found device /dev/vg/lv_swap.',
    27: 'systemd[1]: Activated swap /dev/dm-1.',
    28: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    29: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    30: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    31: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    32: 'systemd[1]: Reloading.',
    33: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    34: 'systemd[1]: Started ACPI event daemon.',
    35: 'systemd[1]: Listening on ACPID Listen Socket.',
    36: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    37: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    38: 'systemd[1]: Mounted /.',
    39: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    40: 'systemd[1]: Found device /dev/dm-1.',
    41: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    42: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    43: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    44: 'systemd[1]: Found device /dev/vg/lv_swap.',
    45: 'systemd[1]: Activated swap /dev/dm-1.',
    46: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    47: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    48: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    49: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    50: 'systemd[1]: Reloading.',
    51: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    52: 'systemd[1]: Started ACPI event daemon.',
    53: 'systemd[1]: Listening on ACPID Listen Socket.',
    54: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    55: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    56: 'systemd[1]: Mounted /.',
    57: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    58: 'systemd[1]: Found device /dev/dm-1.',
    59: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    60: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    61: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    62: 'systemd[1]: Found device /dev/vg/lv_swap.',
    63: 'systemd[1]: Activated swap /dev/dm-1.',
    64: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    65: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    66: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    67: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    68: 'systemd[1]: Reloading.',
    69: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    70: 'systemd[1]: Started ACPI event daemon.',
    71: 'systemd[1]: Listening on ACPID Listen Socket.',
    72: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    73: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    74: 'systemd[1]: Mounted /.',
    75: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    76: 'systemd[1]: Found device /dev/dm-1.',
    77: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    78: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    79: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    80: 'systemd[1]: Found device /dev/vg/lv_swap.',
    81: 'systemd[1]: Activated swap /dev/dm-1.',
    82: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    83: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    84: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    85: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    86: 'systemd[1]: Reloading.',
    87: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    88: 'systemd[1]: Started ACPI event daemon.',
    89: 'systemd[1]: Listening on ACPID Listen Socket.',
    90: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    91: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    92: 'systemd[1]: Mounted /.',
    93: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    94: 'systemd[1]: Found device /dev/dm-1.',
    95: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    96: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    97: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    98: 'systemd[1]: Found device /dev/vg/lv_swap.',
    99: 'systemd[1]: Activated swap /dev/dm-1.',
    100: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    101: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    102: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    103: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    104: 'systemd[1]: Reloading.',
    105: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    106: 'systemd[1]: Started ACPI event daemon.',
    107: 'systemd[1]: Listening on ACPID Listen Socket.',
    108: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    109: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    110: 'systemd[1]: Mounted /.',
    111: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    112: 'systemd[1]: Found device /dev/dm-1.',
    113: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    114: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    115: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    116: 'systemd[1]: Found device /dev/vg/lv_swap.',
    117: 'systemd[1]: Activated swap /dev/dm-1.',
    118: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    119: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    120: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    121: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    122: 'systemd[1]: Reloading.',
    123: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    124: 'systemd[1]: Started ACPI event daemon.',
    125: 'systemd[1]: Listening on ACPID Listen Socket.',
    126: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    127: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    128: 'systemd[1]: Mounted /.',
    129: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    130: 'systemd[1]: Found device /dev/dm-1.',
    131: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    132: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    133: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    134: 'systemd[1]: Found device /dev/vg/lv_swap.',
    135: 'systemd[1]: Activated swap /dev/dm-1.',
    136: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    137: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    138: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    139: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    140: 'systemd[1]: Reloading.',
    141: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    142: 'systemd[1]: Started ACPI event daemon.',
    143: 'systemd[1]: Listening on ACPID Listen Socket.',
    144: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    145: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    146: 'systemd[1]: Mounted /.',
    147: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    148: 'systemd[1]: Found device /dev/dm-1.',
    149: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    150: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    151: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    152: 'systemd[1]: Found device /dev/vg/lv_swap.',
    153: 'systemd[1]: Activated swap /dev/dm-1.',
    154: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    155: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    156: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    157: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    158: 'systemd[1]: Reloading.',
    159: 'systemd[1]: [/lib/systemd/system/docker.service:25] Unknown lvalue \'Delegate\' in section \'Service\'',
    160: 'systemd[1]: Started ACPI event daemon.',
    161: 'systemd[1]: Listening on ACPID Listen Socket.',
    162: 'systemd[1]: Activated swap /dev/mapper/vg-tv_swap.',
    163: 'systemd[1]: Found device /dev/mapper/vg-lv_swap.',
    164: 'systemd[1]: Mounted /.',
    165: 'systemd[1]: Found device /sys/devices/virtual/block/dm-1.',
    166: 'systemd[1]: Found device /dev/dm-1.',
    167: 'systemd[1]: Found device /dev/disk/by-id/dm-name-vg.lv_swap.',
    168: 'systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7'
        'seXGSESWJPCLH55P25.',
    169: 'systemd[1]: Found device /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    170: 'systemd[1]: Found device /dev/vg/lv_swap.',
    171: 'systemd[1]: Activated swap /dev/dm-1.',
    172: 'systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-1v_swap.',
    173: 'systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-YUXAGemchingCumj90SEITMobZyUD2FIRY4EHIVMSb0a7.',
    174: 'systemd[1]: Activated swap /dev/disk/by-uuid/658531ea-be58-44fa-b561-68ed44d3c760.',
    175: 'systemd[1]: Activated swap /dev/vg/lv_swap.',
    176: 'systemd[1]: Starting Synchronise Hardware Clock to System Clock...',
    177: 'systemd[1]: Stopping Session 2336 of user root.',
    178: 'systemd[1]: Stopping Session 2334 of user root.',
    179: 'systemd[1]: Stopping Session 1187 of user root.',
    180: 'systemd[1]: Stopping Session 21 of user root.',
    181: 'systemd[1]: Stopping LVM2 PV scan on device 8:3...',
    182: 'systemd[1]: Stopping system-systemd\x2dfsck.slice.',
    183: 'systemd[1]: Removed slice system-systemd\x2dfsck.slice.',
    184: 'systemd[1]: Stopping User Manager for UID 0...',
    185: 'systemd[28726]: Stopping Default.',
    186: 'systemd[28726]: Stopped target Default.',
    187: 'systemd[28726]: Stopping Basic System.',
    188: 'systemd[28726]: Stopped target Basic System.',
    189: 'systemd[28726]: Stopping Paths.',
    190: 'systemd[28726]: Stopped target Paths.',
    191: 'systemd[28726]: Stopping Timers.',
    192: 'systemd[28726]: Stopped target Timers.',
    193: 'systemd[28726]: Stopping Sockets.',
    194: 'systemd[28726]: Stopped target Sockets.',
    195: 'systemd[28726]: Starting Shutdown.',
    196: 'systemd[28726]: Reached target Shutdown.',
    197: 'systemd[28726]: Starting Exit the Session...',
    198: 'systemd[1]: Stopping Graphical Interface.',
    199: 'systemd[1]: Stopped target Graphical Interface.',
    200: 'systemd[1]: Stopping Multi-User System.',
    201: 'systemd[1]: Stopped target Multi-User System.',
    202: 'systemd[1]: Stopping OpenBSD Secure Shell server...',
    203: 'systemd[1]: Stopping Docker Application Container Engine...',
    204: 'systemd[1]: Stopping Startup script for Plesk control panel server...',
    205: 'systemd[1]: Stopping Startup script for Panel sw-engine...',
    206: 'systemd[1]: Stopping Plesk mail filter service for Postfix...',
    207: 'systemd[1]: Stopping The PHP FastCGI Process Manager...',
    208: 'systemd[1]: Stopping Startup script for nginx service...',
    209: 'systemd[28726]: Received SIGRTHIN+24 from PID 6461 (kill).',
    210: 'systemd[1]: Stopping Plesk Panel...',
    211: 'systemd[1]: Stopped Plesk Panel.',
    212: 'systemd[1]: Stopping Regular background program processing daemon...',
    213: 'systemd[1]: Stopping LSB: Apache2 web server...',
    214: 'dockerd[11639]: times="2017-09-26T23:31:47.560801701-02:00" level-info msg="Processing signal \'terminated\'"'
}


def change_terminal_color_to_green():
    system('color a')


def generate_message_delay():
    minimum_delay = 0
    maximum_delay = 0.400
    delay = uniform(minimum_delay, maximum_delay)
    return delay


def show_message_infinitely():
    line = 0
    message_length = len(message) - 1
    while True:
        print(message[line])
        delay = generate_message_delay()
        sleep(delay)
        if line == message_length:
            line = 0
        else:
            line += 1


if __name__ == '__main__':
    change_terminal_color_to_green()
    show_message_infinitely()
